version: "3.8"

services:

  sdc_upload_videos_api:
    container_name: sdc_upload_videos_api
    build: .
    ports:
      - "8270:80"
    volumes:
      - .:/api
    working_dir: /api
    expose:
      - 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_network

networks:
  local_network:
    external: true