version: "3.8"

services:

  dfeed_td_capacity:
    container_name: dfeed_td_capacity
    build: .
    ports:
      - "8260:80"
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - 80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_network

networks:
  local_network:
    external: true